/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WildernessImport } from './routes/wilderness'
import { Route as PokeboxImport } from './routes/pokebox'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WildernessRoute = WildernessImport.update({
  id: '/wilderness',
  path: '/wilderness',
  getParentRoute: () => rootRoute,
} as any)

const PokeboxRoute = PokeboxImport.update({
  id: '/pokebox',
  path: '/pokebox',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokebox': {
      id: '/pokebox'
      path: '/pokebox'
      fullPath: '/pokebox'
      preLoaderRoute: typeof PokeboxImport
      parentRoute: typeof rootRoute
    }
    '/wilderness': {
      id: '/wilderness'
      path: '/wilderness'
      fullPath: '/wilderness'
      preLoaderRoute: typeof WildernessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokebox': typeof PokeboxRoute
  '/wilderness': typeof WildernessRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokebox': typeof PokeboxRoute
  '/wilderness': typeof WildernessRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokebox': typeof PokeboxRoute
  '/wilderness': typeof WildernessRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokebox' | '/wilderness'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokebox' | '/wilderness'
  id: '__root__' | '/' | '/pokebox' | '/wilderness'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokeboxRoute: typeof PokeboxRoute
  WildernessRoute: typeof WildernessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokeboxRoute: PokeboxRoute,
  WildernessRoute: WildernessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokebox",
        "/wilderness"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokebox": {
      "filePath": "pokebox.tsx"
    },
    "/wilderness": {
      "filePath": "wilderness.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
